/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppClaimsRouteImport } from './routes/_app/claims'
import { Route as AppConnectorsRouteImport } from './routes/_app/connectors'
import { Route as AppLedgerRouteImport } from './routes/_app/ledger'
import { Route as AppPartnersRouteImport } from './routes/_app/partners'
import { Route as AppRecipesRouteImport } from './routes/_app/recipes'
import { Route as AppStatementsRouteImport } from './routes/_app/statements'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ActionsRouteImport } from './routes/api/v1.actions'
import { Route as ApiV1WebhookRouteImport } from './routes/api/v1.webhook'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppClaimsRoute = AppClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ActionsRoute = ApiV1ActionsRouteImport.update({
  id: '/api/v1/actions',
  path: '/api/v1/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WebhookRoute = ApiV1WebhookRouteImport.update({
  id: '/api/v1/webhook',
  path: '/api/v1/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/claims': typeof AppClaimsRoute
  '/connectors': typeof AppConnectorsRoute
  '/ledger': typeof AppLedgerRoute
  '/partners': typeof AppPartnersRoute
  '/recipes': typeof AppRecipesRoute
  '/statements': typeof AppStatementsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/actions': typeof ApiV1ActionsRoute
  '/api/v1/webhook': typeof ApiV1WebhookRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/claims': typeof AppClaimsRoute
  '/connectors': typeof AppConnectorsRoute
  '/ledger': typeof AppLedgerRoute
  '/partners': typeof AppPartnersRoute
  '/recipes': typeof AppRecipesRoute
  '/statements': typeof AppStatementsRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/actions': typeof ApiV1ActionsRoute
  '/api/v1/webhook': typeof ApiV1WebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/claims': typeof AppClaimsRoute
  '/_app/connectors': typeof AppConnectorsRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/partners': typeof AppPartnersRoute
  '/_app/recipes': typeof AppRecipesRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/actions': typeof ApiV1ActionsRoute
  '/api/v1/webhook': typeof ApiV1WebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/claims'
    | '/connectors'
    | '/ledger'
    | '/partners'
    | '/recipes'
    | '/statements'
    | '/api/auth/$'
    | '/api/v1/actions'
    | '/api/v1/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/claims'
    | '/connectors'
    | '/ledger'
    | '/partners'
    | '/recipes'
    | '/statements'
    | '/'
    | '/api/auth/$'
    | '/api/v1/actions'
    | '/api/v1/webhook'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/claims'
    | '/_app/connectors'
    | '/_app/ledger'
    | '/_app/partners'
    | '/_app/recipes'
    | '/_app/statements'
    | '/_app/'
    | '/api/auth/$'
    | '/api/v1/actions'
    | '/api/v1/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ActionsRoute: typeof ApiV1ActionsRoute
  ApiV1WebhookRoute: typeof ApiV1WebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/claims': {
      id: '/_app/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AppClaimsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/actions': {
      id: '/api/v1/actions'
      path: '/api/v1/actions'
      fullPath: '/api/v1/actions'
      preLoaderRoute: typeof ApiV1ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/webhook': {
      id: '/api/v1/webhook'
      path: '/api/v1/webhook'
      fullPath: '/api/v1/webhook'
      preLoaderRoute: typeof ApiV1WebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppClaimsRoute: typeof AppClaimsRoute
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppClaimsRoute: AppClaimsRoute,
  AppConnectorsRoute: AppConnectorsRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ActionsRoute: ApiV1ActionsRoute,
  ApiV1WebhookRoute: ApiV1WebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
